site_name: LeetCode Docs
pages:
- Home: index.md
- Menu: menu.md
- About: about.md
- ZTemplatePage: templateLeetCode.md
theme: readthedocs
site_author: JSSU

repo_url: https://github.com/JSSU/DocLeetCoode/