site_name: LeetCode Docs
pages:
- Home: index.md
- Menu: menu.md
- About: about.md
- Links: usefullinks.md
- Reference: Reference/functionDetails.md 
- Compare: Reference/One VS another.md
- ZTemplatePage: templateLeetCode.md
- "355. Design Twitter" : Leetcode/355 Design Twitter.md 
theme: readthedocs
site_author: JSSU

repo_url: https://github.com/JSSU/DocLeetCoode/